# Generated by Django 4.2.18 on 2025-03-14 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlip', '0002_patentportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('logo', models.ImageField(blank=True, default='na.png', upload_to='logo/%Y/%m/%d', verbose_name='Logo')),
                ('b_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('territory', models.CharField(blank=True, max_length=200, null=True, verbose_name='Territory')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Application Date')),
                ('application_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Application Number')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('registration_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Registration Number')),
                ('classes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classes')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('affidavit', models.DateField(blank=True, null=True, verbose_name='Affidavit')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Name')),
                ('owner_email', models.TextField(blank=True, default='', null=True, verbose_name='Owner Email')),
                ('owner_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Phone')),
                ('owner_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Address')),
                ('owner_vat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner VAT')),
                ('owner_contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Contact')),
                ('agent_name', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Agent Name')),
                ('agent_email', models.TextField(blank=True, default='', null=True, verbose_name='Agent Email')),
                ('agent_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent Phone')),
                ('agent_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent Address')),
                ('agent_vat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent- VAT')),
                ('agent_contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent Contact')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Name')),
                ('group_email', models.TextField(blank=True, default='', null=True, verbose_name='Group Email')),
                ('group_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Address')),
                ('group_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group- Phone')),
                ('group_vat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group VAT ')),
                ('group_contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Contact')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
