# Generated by Django 4.2.18 on 2025-03-23 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlip', '0003_brandportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_vat', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
