# Generated by Django 4.2.18 on 2025-03-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlip', '0006_domainportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_title', models.CharField(max_length=3000)),
                ('logo', models.ImageField(blank=True, default='na.png', upload_to='logo')),
                ('territory', models.CharField(blank=True, max_length=200, null=True)),
                ('d_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Application Date')),
                ('application_no', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('registration_no', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_vat', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_vat', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('group_address', models.CharField(blank=True, max_length=100, null=True)),
                ('group_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('group_vat', models.CharField(blank=True, max_length=100, null=True)),
                ('group_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('inventor', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Inventor')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
