# Generated by Django 4.2.18 on 2025-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlip', '0007_modelportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelportfolio',
            name='logo',
            field=models.ImageField(blank=True, default='na.png', null=True, upload_to='logo'),
        ),
    ]
