# Generated by Django 4.2.18 on 2025-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlip', '0008_alter_modelportfolio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelportfolio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
