# Generated by Django 4.2.18 on 2025-03-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlip', '0009_alter_modelportfolio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandportfolio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
